'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Avm.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property btnLlamar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLlamar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;idioma desc=&quot;en&quot;&gt;
        '''  &lt;tag clave=&quot;disconnect&quot; valor=&quot;Desconectar&quot; /&gt;
        '''  
        '''  &lt;tag clave=&quot;pop_disconnect_question&quot; valor=&quot;¿Desconectar del emulador?&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_exit_question&quot; valor=&quot;AVM está conectado al emulador. ¿Quieres salir?&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_exit_title&quot; valor=&quot;Confirmación de salida&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_kill_question&quot; valor=&quot;¿Matar la instancia del emulador de Android?&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_kill_title&quot; valor=&quot;Matar emulador&quot; /&gt;
        '''
        '''  &lt;tag clave [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;idioma desc=&quot;es&quot;&gt;
        '''  &lt;tag clave=&quot;disconnect&quot; valor=&quot;Desconectar&quot; /&gt;
        '''  
        '''  &lt;tag clave=&quot;pop_disconnect_question&quot; valor=&quot;¿Desconectar del emulador?&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_exit_question&quot; valor=&quot;AVM está conectado al emulador. ¿Quieres salir?&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_exit_title&quot; valor=&quot;Confirmación de salida&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_kill_question&quot; valor=&quot;¿Matar la instancia del emulador de Android?&quot; /&gt;
        '''  &lt;tag clave=&quot;pop_kill_title&quot; valor=&quot;Matar emulador&quot; /&gt;
        '''
        '''  &lt;tag clave [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property es() As String
            Get
                Return ResourceManager.GetString("es", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoAyuda16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoAyuda16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoBateria64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoBateria64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoCall64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoCall64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoConfig48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoConfig48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGps64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGps64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsm64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsm64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmActive16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmActive16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmBusy16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmBusy16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmCancel16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmCancel16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmHeld16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmHeld16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmInbound16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmInbound16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmIncoming16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmIncoming16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmOutbound16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmOutbound16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmUnknown16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmUnknown16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoInfo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoInfo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoManual16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoManual16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuDebug48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuDebug48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuHome64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuHome64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuLogout64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuLogout64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuSalir48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuSalir48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icono_tool64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icono_tool64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoSensores64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoSensores64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoSms64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoSms64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mn_ayuda48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mn_ayuda48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to es.
        '''</summary>
        Friend ReadOnly Property sIdiomas() As String
            Get
                Return ResourceManager.GetString("sIdiomas", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property superior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://jafs.es/aplicaciones/android-virtual-management.
        '''</summary>
        Friend ReadOnly Property sUrlAplicacion() As String
            Get
                Return ResourceManager.GetString("sUrlAplicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to jafs@jafs.es.
        '''</summary>
        Friend ReadOnly Property sUrlCorreo() As String
            Get
                Return ResourceManager.GetString("sUrlCorreo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://github.com/jafs/avm/wiki/Gu%C3%ADa-de-usuario.
        '''</summary>
        Friend ReadOnly Property sUrlManual() As String
            Get
                Return ResourceManager.GetString("sUrlManual", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
