'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.296
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Avm.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property btnLlamar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btnLlamar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;idioma desc=&quot;en&quot;&gt;
        '''  &lt;tag clave=&quot;disconnect&quot; valor=&quot;Disconnect&quot; /&gt;
        '''  &lt;tag clave=&quot;error&quot; valor=&quot;Error&quot; /&gt;
        '''  &lt;tag clave=&quot;logout&quot; valor=&quot;Logout&quot; /&gt;
        '''  &lt;tag clave=&quot;version&quot; valor=&quot;Versión&quot; /&gt;
        '''  &lt;tag clave=&quot;warning&quot; valor=&quot;Warning&quot; /&gt;
        '''
        '''  &lt;tag clave=&quot;err_no_connection&quot; valor=&quot;There is no connection&quot; /&gt;
        '''  &lt;tag clave=&quot;err_call_number&quot; valor=&quot;Enter a valid phone number&quot; /&gt;
        '''  &lt;tag clave=&quot;err_call_prefix&quot; valor=&quot;Enter a valid prefix&quot; /&gt;
        '''  &lt;tag clave=&quot;err_command&quot; valor [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;idioma desc=&quot;es&quot;&gt;
        '''  &lt;tag clave=&quot;disconnect&quot; valor=&quot;Desconectar&quot; /&gt;
        '''  &lt;tag clave=&quot;error&quot; valor=&quot;Error&quot; /&gt;
        '''  &lt;tag clave=&quot;logout&quot; valor=&quot;Cerrar&quot; /&gt;
        '''  &lt;tag clave=&quot;version&quot; valor=&quot;Versión&quot; /&gt;
        '''  &lt;tag clave=&quot;warning&quot; valor=&quot;Atención&quot; /&gt;
        '''
        '''  &lt;tag clave=&quot;err_no_connection&quot; valor=&quot;No hay conexión&quot; /&gt;
        '''  &lt;tag clave=&quot;err_call_number&quot; valor=&quot;Introduce un número de teléfono válido&quot; /&gt;
        '''  &lt;tag clave=&quot;err_call_prefix&quot; valor=&quot;Introduce un prefijo válido&quot; /&gt;
        '''  &lt;tag clave=&quot;err_ [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property es() As String
            Get
                Return ResourceManager.GetString("es", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoAyuda16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoAyuda16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoBateria64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoBateria64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoCall64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoCall64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoConfig48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoConfig48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGps64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGps64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsm64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsm64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmActive16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmActive16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmBusy16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmBusy16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmCancel16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmCancel16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmHeld16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmHeld16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmInbound16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmInbound16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmIncoming16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmIncoming16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmOutbound16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmOutbound16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoGsmUnknown16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoGsmUnknown16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoInfo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoInfo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoManual16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoManual16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuDebug48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuDebug48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuHome64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuHome64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuLogout64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuLogout64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoMenuSalir48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoMenuSalir48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icono_tool64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icono_tool64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoSensores64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoSensores64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icoSms64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icoSms64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mn_ayuda48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mn_ayuda48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a es.
        '''</summary>
        Friend ReadOnly Property sIdiomas() As String
            Get
                Return ResourceManager.GetString("sIdiomas", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property superior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a http://jafs.es/aplicaciones/android-virtual-management.
        '''</summary>
        Friend ReadOnly Property sUrlAplicacion() As String
            Get
                Return ResourceManager.GetString("sUrlAplicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a jafs@jafs.es.
        '''</summary>
        Friend ReadOnly Property sUrlCorreo() As String
            Get
                Return ResourceManager.GetString("sUrlCorreo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
